services:
  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ed_machina
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - src/.env
    environment:
      SQL_DATABASE_URL: postgresql://postgres:postgres@db:5432/ed_machina
      SQL_TEST_DATABASE_URL: postgresql://postgres:postgres@db:5432/ed_machina_test
      DB: postgresql://postgres:postgres@db:5432/ed_machina
      DB_TEST: postgresql://postgres:postgres@db:5432/ed_machina_test

  tests:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    volumes:
      - ./src/:/usr/src/
    depends_on:
      - db
    env_file:
      - src/.env
    environment:
      SQL_DATABASE_URL: postgresql://postgres:postgres@db:5432/ed_machina
      SQL_TEST_DATABASE_URL: postgresql://postgres:postgres@db:5432/ed_machina_test
      DB: postgresql://postgres:postgres@db:5432/ed_machina
      DB_TEST: postgresql://postgres:postgres@db:5432/ed_machina_test
    command: ["sleep", "infinity"]
volumes:
  postgres_data:
